services:
    nginx:
        build: ./image
        ports:
            - 443:443
            - 80:80
            - 7851:7851
            - 7852:7852
            - 7853:7853
            - 5001:5001
        restart: always
        container_name: nginx
        networks:
            - behind-nginx
        volumes:
            - letsencrypt:/etc/letsencrypt

volumes:
    letsencrypt:
        driver: local
        driver_opts:
            o: bind
            type: none
            device: /etc/letsencrypt

networks:
    behind-nginx:
        name: behind-nginx-network
